service:
  type: NodePort
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
    NodePort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
    NodePort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
    NodePort: 443
  - name: http2-9080
    port: 9080
    protocol: TCP
    targetPort: 9080
    NodePort: 9080
  - name: https-9443
    port: 9443
    protocol: TCP
    targetPort: 9443
    NodePort: 9443
#TODO disable sidecar injection on ceph prepare pods?