- name: Pull kubeconfig file from VM node
  hosts: kube-node-0  # Replace with the appropriate host group or hostname
  become: true
  tasks:
    - name: Fetch kubeconfig file
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        flat: yes
