---
- name: Deploy Kubernetes Tasks
  hosts: all  # Specify the hosts from your inventory file
  become: yes
  gather_facts: yes
  tasks:
    - name: Include tasks from the tasks directory
      include_tasks: "{{ item }}"
      loop:
        - tasks/00-requirements.yml
        - tasks/01-crio.yml
        - tasks/02-kube-install.yml
        - tasks/03-kube-cluster.yml
        - tasks/04-calico.yml
        # - tasks/04-cilium.yml ## Uncomment this line to use Cilium instead of Calico
        - tasks/05-kube-join-nodes.yml
        - tasks/disable-swap.yml
        - tasks/requirements.yml
